swagger: '2.0'

info:
  version: "1.0.0"
  title: College Model

definitions:
  Course:
    type: object
    properties:
      courseName:
        type: string
        description: Name of the Course
      courseId:
        type: string
        description: Unique course identifier